config/routes.rb
Rails.application.routes.draw do

  get '/', to: "welcome#index"

  get '/auth/spotify/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :artists do
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:index, :show, :edit, :update]
  resources :playlists, only: [:index, :new, :create, :show, :edit, :update]
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_from_auth(auth)
    User.find_or_create_by(
      provider: auth["provider"],
      uid: auth["info"]["id"],
      name: auth["info"]["display_name"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      flash[:error] = "#{@artist.errors.full_messages.join(", ")}"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.delete
    redirect_to artists_path
  end

private

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update]

  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      redirect_to @playlist
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      render :edit
    end
  end


private

  def playlist_params
      params.require(:playlist).permit(:name, song_ids: [])
  end

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to playlists_path
    end
  end

  def destroy
    session.clear
    redirect_to playlists_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist, only: [:new, :create]

  def index
    @songs = Song.order(:title)
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.new(song_params)
      if @song.save
        redirect_to song_path(@song)
      else
        flash[:error] = "#{@song.errors.full_messages.join(", ")}"
        render :new
      end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def show
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render :edit
    end
  end

private
  def song_params
    params.require(:song).permit(:title)
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>

<%= render partial: "shared/errors", locals: { target: @artist} %>


  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>

<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render partial: "form" %>

app/views/artists/index.html.erb
<div class="container">

<h1>All Artists</h1>


<h4><%= link_to "New Artist", new_artist_path, class: "btn btn-primary" %></h4>


<table class="table table-hover">
    <% @artists.each do |artist| %>
      <tr>
      <td><%= link_to artist.name, artist_path(artist) %></td>
      <% end %>
    </tr>
    <tr><td></td></tr>
  </table>

</div>

</div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render partial: "form" %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<div class="thumbnail">
<%= image_tag @artist.image_path%>
</div>

<%= link_to "Edit Artist", edit_artist_path, class: "btn btn-warning" %>
<%= link_to "Delete Artist", artist_path(@artist), method: :delete, class: "btn btn-danger" %>
<%= link_to "New Song", new_artist_song_path(@artist), class: "btn btn-success" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">MixMaster</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li> Welcome, <%= current_user.name %></li>
          <li><%= link_to "Sign out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in with Spotify", "/auth/spotify" %></li>
        <% end %>
    </ul>


</nav>

<% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "flash_#{type}" %>
      <% end %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>

<%= render partial: "shared/errors", locals: { target: @playlist} %>

  <%= f.label :name %>
  <%= f.text_area :name %>

  <% Song.all.each do |song| %>
    <div>
      <%= check_box_tag(:song_ids, song.id, false, :name => 'playlist[song_ids][]', id: "song-#{song.id}") %>
      <%= song.title %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit Playlist</h1>

<%= render partial: "form" %>

app/views/playlists/index.html.erb
<h1>All Playlists</h1>

<ul>
  <% @playlists.each do |playlist| %>
  <li><%= link_to playlist.name, playlist %></li>
  <% end %>
</ul>

<%= link_to "New Playlist", new_playlist_path, class: "btn btn-primary" %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render partial: "form" %>

app/views/playlists/show.html.erb
<h1><%=@playlist.name %></h1>

<ul>
<%= @playlist.songs.each do |song| %>
  <li> <%= link_to song.title, song %></li>
  <% end %>
</ul>

<%= link_to "Edit", edit_playlist_path %>

app/views/songs/_form.html.erb
<%= form_for([@artist, @song]) do |f| %>

<%= render partial: "shared/errors", locals: { target: @song} %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render partial: "form" %>

app/views/songs/index.html.erb
<h1>All Songs</h1>

<table class="table table-hover">
    <% @songs.each do |song| %>
      <tr>
      <td><%= link_to song.title, song %></td>
      <% end %>
    </tr>
    <tr><td></td></tr>
  </table>

app/views/songs/new.html.erb
<h1>New Song</h1>

<p>Add a New Song for <%= @artist.name %></p>

<%= render partial: "form" %>

<%= link_to @artist.name, artist_path(@artist) %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>

<%= link_to @song.artist.name, artist_path(@song.artist_id) %>

<%= link_to "Edit", edit_song_path %>

app/views/welcome/index.html.erb
  <ul class="nav navbar-nav navbar-center">
    <li><%= link_to "Playlists", playlists_path, class: "btn btn-default" %></li>
    <li><%= link_to "Artists", artists_path, class: "btn btn-default" %></li>
    <li><%= link_to "Songs", songs_path, class: "btn btn-default" %></li>
  </ul>


<div class="welcome">
</div>